import type { Specialty, SpecialtySlug } from '../types';

/**
 * Stammdaten für 12 Fachrichtungen. Die UI übersetzt über i18n (`specialty.<slug>`);
 * name_de/name_en werden zusätzlich in der Datenbank gepflegt (Dashboard, Export).
 */
export const SPECIALTIES: Specialty[] = [
  {
    id: 1,
    slug: 'allgemeinmedizin',
    nameDe: 'Allgemeinmedizin',
    nameEn: 'General practice',
    icon: 'Stethoscope',
  },
  {
    id: 2,
    slug: 'innere-medizin',
    nameDe: 'Innere Medizin',
    nameEn: 'Internal medicine',
    icon: 'HeartPulse',
  },
  {
    id: 3,
    slug: 'kinder-jugendmedizin',
    nameDe: 'Kinder- und Jugendmedizin',
    nameEn: 'Paediatrics',
    icon: 'Baby',
  },
  {
    id: 4,
    slug: 'frauenheilkunde',
    nameDe: 'Frauenheilkunde',
    nameEn: 'Gynaecology',
    icon: 'Venus',
  },
  { id: 5, slug: 'hno', nameDe: 'Hals-Nasen-Ohren', nameEn: 'Ear, nose & throat', icon: 'Ear' },
  { id: 6, slug: 'augenheilkunde', nameDe: 'Augenheilkunde', nameEn: 'Ophthalmology', icon: 'Eye' },
  { id: 7, slug: 'dermatologie', nameDe: 'Dermatologie', nameEn: 'Dermatology', icon: 'Hand' },
  { id: 8, slug: 'orthopaedie', nameDe: 'Orthopädie', nameEn: 'Orthopaedics', icon: 'Bone' },
  { id: 9, slug: 'zahnmedizin', nameDe: 'Zahnmedizin', nameEn: 'Dentistry', icon: 'Toothbrush' },
  { id: 10, slug: 'neurologie', nameDe: 'Neurologie', nameEn: 'Neurology', icon: 'Brain' },
  { id: 11, slug: 'urologie', nameDe: 'Urologie', nameEn: 'Urology', icon: 'Droplet' },
  {
    id: 12,
    slug: 'psychiatrie-psychotherapie',
    nameDe: 'Psychiatrie und Psychotherapie',
    nameEn: 'Psychiatry & psychotherapy',
    icon: 'MessageCircleHeart',
  },
];

export const specialtyBySlug = (slug: SpecialtySlug) => SPECIALTIES.find((s) => s.slug === slug);
export const specialtyById = (id: number) => SPECIALTIES.find((s) => s.id === id);

/** Leistungskatalog (Schlüssel, Übersetzung über i18n `service.<key>`). */
export const SERVICE_KEYS = [
  'checkup',
  'vaccination',
  'ecg',
  'ultrasound',
  'lab',
  'allergy_test',
  'child_checkups',
  'prevention',
  'skin_screening',
  'eye_pressure',
  'vision_test',
  'hearing_test',
  'dental_cleaning',
  'dental_emergency',
  'sports_medicine',
  'acupuncture',
  'home_visits',
  'video_consultation',
  'travel_medicine',
  'pain_therapy',
  'pregnancy_care',
  'sleep_diagnostics',
  'talk_therapy',
] as const;
export type ServiceKey = (typeof SERVICE_KEYS)[number];

export const SERVICES_BY_SPECIALTY: Record<SpecialtySlug, ServiceKey[]> = {
  allgemeinmedizin: [
    'checkup',
    'vaccination',
    'ecg',
    'lab',
    'home_visits',
    'travel_medicine',
    'prevention',
  ],
  'innere-medizin': ['checkup', 'ecg', 'ultrasound', 'lab', 'sleep_diagnostics', 'prevention'],
  'kinder-jugendmedizin': [
    'child_checkups',
    'vaccination',
    'allergy_test',
    'hearing_test',
    'vision_test',
  ],
  frauenheilkunde: ['prevention', 'pregnancy_care', 'ultrasound', 'vaccination'],
  hno: ['hearing_test', 'allergy_test', 'ultrasound'],
  augenheilkunde: ['vision_test', 'eye_pressure', 'prevention'],
  dermatologie: ['skin_screening', 'allergy_test', 'prevention'],
  orthopaedie: ['sports_medicine', 'ultrasound', 'acupuncture', 'pain_therapy'],
  zahnmedizin: ['dental_cleaning', 'dental_emergency', 'prevention'],
  neurologie: ['sleep_diagnostics', 'pain_therapy'],
  urologie: ['prevention', 'ultrasound', 'lab'],
  'psychiatrie-psychotherapie': ['talk_therapy', 'video_consultation'],
};

/** Verteilung der ~60 Demo-Praxen auf Fachrichtungen (realistische Gewichtung). */
export const PRACTICE_MIX: [SpecialtySlug, number][] = [
  ['allgemeinmedizin', 14],
  ['zahnmedizin', 7],
  ['kinder-jugendmedizin', 5],
  ['frauenheilkunde', 5],
  ['innere-medizin', 5],
  ['augenheilkunde', 4],
  ['hno', 4],
  ['orthopaedie', 4],
  ['dermatologie', 3],
  ['neurologie', 3],
  ['urologie', 3],
  ['psychiatrie-psychotherapie', 3],
];

export const PRACTICE_PREFIX: Record<SpecialtySlug, string[]> = {
  allgemeinmedizin: ['Hausarztpraxis', 'Hausärzte', 'Gemeinschaftspraxis'],
  'innere-medizin': ['Internistische Praxis', 'Innere Medizin'],
  'kinder-jugendmedizin': ['Kinderarztpraxis', 'Kinder- und Jugendärzte'],
  frauenheilkunde: ['Frauenarztpraxis', 'Frauenärztinnen'],
  hno: ['HNO-Praxis'],
  augenheilkunde: ['Augenarztpraxis', 'Augenärzte'],
  dermatologie: ['Hautarztpraxis'],
  orthopaedie: ['Orthopädie', 'Orthopädische Praxis'],
  zahnmedizin: ['Zahnarztpraxis', 'Zahnmedizin'],
  neurologie: ['Neurologische Praxis'],
  urologie: ['Urologische Praxis'],
  'psychiatrie-psychotherapie': ['Praxis für Psychotherapie', 'Psychiatrische Praxis'],
};

/** Fiktive Ortsbezeichnungen (Namens- und Adressbestandteile der Demo-Praxen). */
export const PLACE_NAMES = [
  'Lindenhof',
  'Kastanienhof',
  'Sonnenhang',
  'Brunnenhof',
  'Mühlbach',
  'Lerchenfeld',
  'Rosengarten',
  'Ahornhain',
  'Ulmenhof',
  'Weidenbach',
  'Birkenallee',
  'Eichenhain',
  'Holunderhof',
  'Talblick',
  'Wiesengrund',
  'Fliederhof',
  'Erlenhof',
  'Quellbach',
  'Kirschgarten',
  'Nussbaumhof',
  'Hainbuche',
  'Schlehenweg',
  'Sternwiese',
  'Apfelhof',
  'Mohnfeld',
  'Lavendelhof',
  'Ginsterhof',
  'Wacholderhang',
  'Weißdornhof',
  'Sonnentau',
  'Bergblick',
  'Auenpark',
  'Fichtenhain',
  'Kiefernweg',
  'Mirabellenhof',
  'Rotdornhof',
  'Schwalbenhof',
  'Taubenfeld',
  'Uferweg',
  'Vogelsang',
  'Waldrand',
  'Zedernhof',
  'Hagebuttenweg',
  'Johannisgarten',
  'Kornblumenfeld',
  'Lindenplatz',
  'Marktblick',
  'Obstwiese',
  'Pappelallee',
  'Quittenhof',
  'Rainfarnweg',
  'Sanddornhof',
  'Thymianweg',
  'Veilchenhof',
  'Wegwarte',
  'Zitronenhof',
  'Malvenhof',
  'Distelfeld',
  'Efeuhof',
  'Feldahorn',
  'Glockenblume',
  'Heideweg',
];

export const STREET_SUFFIX = ['', 'straße', 'weg', 'allee'] as const;

export const FIRST_NAMES = [
  'Lea',
  'Jonas',
  'Miriam',
  'Felix',
  'Hanna',
  'Elias',
  'Sophie',
  'Tobias',
  'Clara',
  'David',
  'Nora',
  'Paul',
  'Amira',
  'Lukas',
  'Julia',
  'Can',
  'Marie',
  'Niklas',
  'Leonie',
  'Matteo',
  'Johanna',
  'Emil',
  'Selin',
  'Ben',
  'Katharina',
  'Tim',
  'Ida',
  'Moritz',
  'Ella',
  'Jan',
];

export const LAST_NAMES = [
  'Brandt',
  'Seidel',
  'Kühn',
  'Vogt',
  'Arnold',
  'Lindner',
  'Engel',
  'Pohl',
  'Horn',
  'Busch',
  'Sauer',
  'Kraus',
  'Ernst',
  'Frank',
  'Thiel',
  'Lorenz',
  'Winter',
  'Sommer',
  'Haas',
  'Böhm',
  'Yilmaz',
  'Nowak',
  'Petrović',
  'Kaya',
  'Albrecht',
  'Graf',
  'Jäger',
  'Roth',
  'Stein',
  'Ludwig',
];

/** Sprachen neben Deutsch mit Wahrscheinlichkeit. */
export const EXTRA_LANGUAGES: [string, number][] = [
  ['en', 0.55],
  ['tr', 0.15],
  ['ru', 0.1],
  ['ar', 0.1],
  ['pl', 0.08],
  ['fr', 0.06],
  ['es', 0.05],
  ['uk', 0.06],
];

/** Taktung in Minuten je Fachrichtung. */
export const SLOT_MINUTES: Record<SpecialtySlug, number> = {
  allgemeinmedizin: 15,
  'innere-medizin': 20,
  'kinder-jugendmedizin': 15,
  frauenheilkunde: 20,
  hno: 15,
  augenheilkunde: 20,
  dermatologie: 15,
  orthopaedie: 20,
  zahnmedizin: 30,
  neurologie: 30,
  urologie: 20,
  'psychiatrie-psychotherapie': 50,
};

/**
 * Fiktive Telefonnummern aus dem von der Bundesnetzagentur für Film/Fernsehen
 * reservierten Bereich (069 90009 xxx) – niemand wird versehentlich angerufen.
 */
export const DEMO_PHONE_PREFIX = '+49 69 90009 ';
